trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'YourDockerRegistryConnection'  # Nombre de la conexión al registro de Docker en Azure DevOps
    repository: 'your-docker-repo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    # Ejecutar pruebas unitarias
    python -m unittest discover -s tests -p '*_test.py'
  displayName: 'Run unit tests'

- task: Docker@2
  inputs:
    containerRegistry: 'YourDockerRegistryConnection'
    repository: 'your-docker-repo'
    command: 'push'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
