
# Definición de la etapa de trabajo
trigger:
  branches:
    include:
      - main
    exclude:
      - azure-pipelines.yaml


pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build_And_Test
  displayName: 'Build and Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      
  - script: |
      python -m pip install --upgrade pip
      pip install -r src/requirements.txt
    displayName: 'Install dependencies'
  
  - script: |
      pytest  # Ejecutar pruebas unitarias con pytest
    displayName: 'Run tests'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'  # Formato de los resultados de las pruebas
      testResultsFiles: '**/TEST-*.xml'  # Patrón para buscar los archivos de resultados de pruebas
    displayName: 'Publish Test Results'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'  # Carpeta raíz de los archivos a archivar
      includeRootFolder: false  # No incluir la carpeta raíz en el archivo
      archiveType: 'zip'  # Tipo de archivo a crear
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'  # Ruta y nombre del archivo de artefacto
      replaceExistingArchive: true
    displayName: 'Archive artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Ruta del directorio de artefactos a publicar
      artifactName: 'drop'  # Nombre del artefacto
    displayName: 'Publish artifact'
