apiVersion: v1
kind: Namespace
metadata:
  name: tech-prod
---
apiVersion: v1
kind: Pod
metadata:
  name: python-microservice-pod
  namespace: tech-prod
  labels:
    app: python-microservice
spec:
  nodeSelector:
    nodetype: docker-desktop
  containers:
  - name: python-microservice-container
    image: jguzman07/millionrepotest:latest
    # resources:
    #   limits:
    #     memory: "3Gi" # Para asignar 3Gb de memory se puede cambiar a 3Gi
    #     cpu: "1"
    ports:
    - containerPort: 80
    env:
    - name: environment
      value: "production"
    - name: internal_network
      value: "internal prod"
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tech-prod-svc
  namespace: tech-prod
  labels:
    app: python-microservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: python-microservice
