
# Definición de la etapa de trabajo
trigger:
  branches:
    include:
      - main
    exclude:
      - azure-pipelines.yaml


pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build_And_Test
  displayName: 'Build and Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      
  - script: |
      python -m pip install --upgrade pip
      pip install pytest
      pip install pytest-junitxml
      pip install --upgrade beautifulsoup4
      pip install -r src/requirements.txt
    displayName: 'Install dependencies'
  
  - script: |
      export PYTHONPATH=$(pwd)/src
      pytest --junitxml=results.xml
    displayName: 'Run tests'
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'results.xml'
    displayName: 'Publish Test Results'
  
  - script: |
      date=$(date +'%Y%m%d-%H%M%S')
        echo "##vso[task.setvariable variable=BuildDateTime]$date"
    displayName: 'Set Build DateTime Variable'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)_$(BuildDateTime).zip'
      replaceExistingArchive: true
    displayName: 'Archive artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
    displayName: 'Publish artifact' 
